# Generated by Django 2.2.10 on 2021-10-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_policy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
