# Generated by Django 2.2.10 on 2021-10-24 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_test3_win_sec_center_bad_states_test7_windows_hotfixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test6_OS_Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OSName', models.CharField(max_length=200)),
                ('OSVersion', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
